### ISSUE TITLE
Cooling System Redesign

### ISSUE THREAD

**Issue by chadjmccolm** [UVicFH/Home#11]
### Context

We need a thermostat and housing to prevent under-cooling in the engine. The operating temperature in the manual is 248 degrees Fahrenheit. 

We also want to add the new radiator and get all the hoses setup for that.

### Outcomes

Here are the goals of this project:
- cool the engine to the desired temperature
- choose an appropriate thermostat
- implement the new radiator
- chose appropriate hoses and connections for the links

### Constraints

Notable constraints are as follows: 
- minimum hose distance cannot be decreased
- new radiator must be used

### Related Issues

This is under the powertrain umbrella #10 .

**Comment by chadjmccolm** [comment]
The radiator was spec'd to have an inlet temperature of 180F so that's what we'll use to ensure we are within the cooling ability of our radiator within the safety factor specified in the MECH 459 report on this topic (on drive under cooling systems). 

![capture](https://user-images.githubusercontent.com/22900772/27784204-3cd3d32c-5f8e-11e7-9dc9-748d39537dd1.PNG)

**Comment by chadjmccolm** [comment]
A thermostat was purchased from Lordco with a grooved gasket. The thermostat was a Gates 33611 and the gasket was a Gates 33708. The thermostat will be modelling approximately and heated up to measure how the length changes at and above the operating temperature chosen.

**Comment by chadjmccolm** [comment]
A sketch was produced to save modelling time because of the geometry. Recommended dimensions are double underlined. Lower housing depth has yet to be decided but must be between the values specified for the fully expanded and contracted thermostat. 

![photoscan](https://user-images.githubusercontent.com/22900772/27802702-52a173e8-5fda-11e7-9fd5-33e7ef503224.jpg)

**Comment by chadjmccolm** [comment]
Interesting development: limitations on anti-corrosive materials was unfounded. The coolant system must be 100% water according to the rules. 

![nocoolant](https://user-images.githubusercontent.com/22900772/27933464-6c373bca-6256-11e7-946d-1d714cf9e248.PNG)

**Comment by chadjmccolm** [comment]
Following today's design review these changes will be made to the model:
- [x] move the lip to the end of where the hose attaches: increases machinability and removes redundant material
- [x] switch to two bolt design of R2 for the connector: allows easier access to attach the inlet and improves elegance of the design
- [x] Make the ID the same for the two outlets: allows the housing to be mounted on a rod for manufacturing 
- [x] Lock all concentric bits in the model: reduces model system use
- [ ] ~~Match hose OD to top and bottom so the hose curve flows into the housing: aesthetic~~
  - removed because this would change the pitch of the diagonal cut on the outside and inside
- [x] Make the bores tighter around the thermostat and create a straight bore on top versus the current slant: tighter is better if the machining time is the same

What we need (will be purchased tomorrow):
- [x] G311-063 hose from Green-Line (5ft)
- [x] 1' length of 3.5" aluminum 6061-T6 from metal supermarket
- [ ] 6x M5 x 20 flathead Torx high-tensile steel fasteners (only need 2 but it's better to keep some in stock because we will lose some eventually and they're a very generic size

**Comment by isaaccormack** [comment]
R4 thermostat will include:
-thinner wall by rodney's discretion
-smaller OD of overall piece through minimizing clamping jaws size
-an elbow to hold the on thermostat piece from

**Comment by smithbeuvic** [comment]
Design review with Rodney resulted in the decision to use a bolt-on insert design with O-Ring. He was reluctant to make such a large pipe thread (M20) and confirmed that straight thread and pipe tape will not seal. 

Looks like fabrication is starting tuesday morning ( July 18th ) or wednesday morning. 

Still unsure if we can trade stock material with Rodney...

**Comment by smithbeuvic** [comment]
Fabrication commenced friday morning and will continue in the week of July 23rd in the Mornings. The firehydrant of aluminum stock was sucessfully traded for appropriate stock. The drawing package looks good, will update and add notes as fabrication continues.

**Comment by chadjmccolm** [comment]
A sketch of the rejoiner part has been completed with some notes. @ciaraduesterwald will be modelling this with my help where necessary. 

![photoscan](https://user-images.githubusercontent.com/22900772/28859106-4fd0bbf0-770a-11e7-9ff7-39829c4e427c.jpg)

**Comment by smithbeuvic** [comment]
We would use pipe stock for this not the 1" solid stock already bought for the thermostat body.

**Comment by chadjmccolm** [comment]
How would we do the ends then? Turn the rings and shrink fit them on?

**Comment by smithbeuvic** [comment]
Max size of circular hole in b-b is 0.5" were not allowed to drill into or out of non flat surfaces in the shop. Will have to finish in q-hut. I might find an alternative.

**Comment by smithbeuvic** [comment]
Sorry Chad. Just use NOM inner diam 0.5" and NOM outer diam 1" we can machine lip from there. 1"x.25" pipe

**Comment by chadjmccolm** [comment]
I think it looks a little funky with the 0.75 OD 0.5 ID main pipe but I don't really want to change the inner diameters where they meet because I don't want to accidentally pressurize one stream. Something we should think about though. A model is complete on GrabCAD under "2017 Formula Car\2017 Car CAD\Cooling System Rejoiner\R1 - Basic\". 

Let me know if you have any suggestions or changes and if not we can get some drawings and machine it.

**Comment by chadjmccolm** [comment]
2 O-Rings were purchased because their cost was insignificant. A Green line 00093-10 was chosen to match the design spec. A M3 bottoming tap was also purchased for the insert mounting holes.

**Comment by chadjmccolm** [comment]
Regarding the joiner a T junction was purchased instead of a wye. I'd have liked to use a wye but the cost benefit wasn't there. I inspected a few new KTM bikes that they all used T junctions so I'm assuming that's the industry standard. Pics of inspection in "Google Drive\Mechanical\2017-2018\Projects\Thermostat Housing\Tee Junction On New Bikes"

The water pump inlet was also a 7/8 inlet instead of a 3/4 but a 3/4 has been used in the past. It's currently impossible to get on but I'll try again with a heat gun and some lube.

**Comment by chadjmccolm** [comment]
Cooling system needs to be tested with a fan on it. Testing was only done without a fan so far due to time constraints and the temperature did not stabilize. The [engine review doc](http://goo.gl/YWCBNp) can provide info on the current bench setup and the startup procedure. Please consult with me first to make sure everything checks out and you understand what's going on before starting the car.

**Comment by chadjmccolm** [comment]
Testing was done with a fan and system temperature was stable.
