### ISSUE TITLE
2017-2018 Season Objectives

### ISSUE THREAD

**Issue by SilverFarmer** [UVicFH/Home#2]
2017-2018 Season Objectives

**Administration/Policy:**

- [ ] Develop written documentation for General Q-Hut Safety 
- [ ] Develop written documentation for high voltage safety
- [ ] Develop written documentation for Q-Hut machine shop safety
- [ ] Create/document UVic hybrid specific CAD standards and naming conventions
- [ ] Develop procedure for working with GrabCAD
- [ ] Develop SolidWorks tutorials for new members
- [ ] Develop Altium tutorials for new members
- [ ] Organize and maintain Google Drive/Github/Slack/GrabCAD
- [ ] Organize vehicle testing proceedure like what is found here, [Testing](https://docs.google.com/document/d/1gfh8MA8amyZFqMY7YMZNJMVl4RyFSolNDQFK7sGGV80/edit?usp=sharing) and the [Site Map](https://drive.google.com/open?id=0B27HcLZ-4MzudHczV3NjdGVPdnc) for testing
- [ ] Organize spill response proceedure, [Spill Response](https://docs.google.com/document/d/1IDxYWwre4zD5RBIRz9h6m5m8eo8W-ANNaIErHYaOU8k/edit)

**Recruitment:**

- [ ] Recruit and retain 15 new members (5 Mechanical, 5 Electrical, 5 Software)
- [ ] Prepare a presentation for the clubs presentation day (new format promoted this year by ESS)
- [ ] Have every current member bring at least one potential recruit to at least one team meeting

**Sponsorship/Fundraising:**

- [ ] Raise $15,000 through sponsorship's and grants (this amount is the bare minimum we need to raise just to cover essential projects and pay the competition entry fee)
- [ ] Maintain solid relationships and communication with important sponsors (i.e. PED)
- [ ] Follow through on sponsorship agreements (mentions on social media, decals on car, etc.)
- [ ] Prepare and present debrief to GM to obtain $5K (USD?)
- [ ] Ask friends and family to contribute towards $10K crowdfunding goal (currently at $1,700 with 1 month left) 
[2016 sponsor information](https://drive.google.com/open?id=1fozs9K5IZaOH1MzmUOYpq2zOt82iBbR3Csh8or2CimE)

**Social Media:**

- [ ] Post a minimum of 1 new entry per month to facebook/website/instagram

**Mechanical:**

- [ ] Design/Fab Frame
- [ ] Poretrain configuration 
- [ ] Design/Fab Suspension
- [ ] Design/Fab Firewall
- [ ] Design/Fab Packaging
- [ ] Design/Fab Mounts
- [ ] Design/Fab Nosecone/bodywork
- [ ] Shim or Rebuild Engine
- [ ] Complete CAD Master Assembly
- [ ] Brakes
- [ ] Design/Fab New Gas Tank

**Electrical:**

- [ ] Debug and test rear power distribution board
- [ ] Debug and test wiring harness
- [ ] Debug and test AMS

**Competition Documents and Logistics:**

- [ ] Register for competition
- [ ] Organize transportation to competition
- [ ] Structural Equivalency Spreadsheet (SES)
- [ ] Project Management Plan
- [ ] Electrical System Form 1 (ESF-1)
- [ ] Fuel Request
- [ ] Program Information Sheet
- [ ] Interim Project Report
- [ ] Impact Attenuator Data
- [ ] Site Pre-Registration
- [ ] Electrical System Form 2 (ESF-2)
- [ ] Failure Modes and Effects Analysis (FMEA)
- [ ] Design Report
- [ ] Sustainability Report
- [ ] Design Specifications Sheet

**Comment by smithbeuvic** [comment]
documents like this were used in the past for project goals
https://drive.google.com/open?id=0B27HcLZ-4MzuUkdqOGVualptbHc
