### ISSUE TITLE
Preliminary Chassis Design Research & Objectives

### ISSUE THREAD

**Issue by SilverFarmer** [UVicFH/Home#5]
### Context

For the 2018 racing season, the UVic Formula Hybrid team will be designing and fabricating a new chassis. As this is a major project that has a significant influence on the cars performance it must be researched thoroughly to ensure the final design is optimized for the team's objectives.

### Outcomes

- [x] Read chassis design texts specifically geared towards racing suspensions (2-3 minimum)

- [x] Gain a solid understanding of the chassis design process and industry best practices

- [x] Develop objectives and goals for the new chassis design 

### Relevant Texts
1 - How to make your car handle - Fred Puhn
https://drive.google.com/file/d/0B4eb3g6wMmHrS2hlOXRBTVp5UHM/view?usp=sharing
Straightforeward overall intro to vehicle dynamics. 

2 - Racecar Vehicle dynamics - Milliken
https://drive.google.com/file/d/0B4eb3g6wMmHrUTlmQnVzcFlVckU/view?usp=sharing
So called "Holy bible" of vehicle dynamics. 4x as long as 'how to make your car handle'.

3 - Racing and Sports Car Chassis Design - Costin and Phipps
Paper copy, In the Hybrid shop or with Bennett Smith.

4 - [Science of Vehicle Dynamics - Massimo Guiggiani](https://drive.google.com/file/d/0B4eb3g6wMmHrYnM3d2hST25GS00/view?usp=sharing)

5 - Any thing Geoff wrote about vehicle dynamics - Geoff Scott
[mech459](https://drive.google.com/open?id=0B27HcLZ-4MzuNWpuUDFnSE1yUUE)
[more reports](https://drive.google.com/drive/folders/0B4eb3g6wMmHrMWlVbzRtMzF1aGM?usp=sharing)

6 - FSAE internet forums
like [this one](http://www.fsae.com/forums/showthread.php?1834-BOOK-LIST-to-reference-for-car-design) that lists more relevant texts! 

7 - Design Reports or Thesis from other teams
[Worcester University 2009 FSAE Project Report](https://drive.google.com/open?id=0B27HcLZ-4MzuU3RoMFV1TG02a2s)
[Lawrence Tech 2002 FSAE suspension design](https://drive.google.com/open?id=0B27HcLZ-4MzuQWwwRzV5dHpRaGc)

### Goals for new chassis design
- reduce weight by 20%
- retain 90% of current torsional rigidity
- lower COM by atleast 25.4 mm
- innovatively package critical vehicle components i.e. engine/motor mounting and configuration
- Introduce at least 1 innovation to the suspension
- Keep principles of suspension the same ( we have a winning design currently )
- Keep uprights, shocks, springs, pneumatic antiroll.

**Comment by MrMikeGrant** [comment]
@smithbeuvic Please add a list of the chassis design texts you are reading and where team members can located them on (i.e. Google Drive). It would be great if you could order them from most critical to least critical!

**Comment by smithbeuvic** [comment]
ok ;), not a professional yet so it will be my opinion

**Comment by smithbeuvic** [comment]
we still need to get all the components measured and modelled
