### ISSUE TITLE
2018 Budget needed to complete the ESS club funding application

### ISSUE THREAD

**Issue by smithbeuvic** [UVicFH/Home#7]
### Project Tiltle - Approx Cost - Description

Chassis - 1500( Geoff's estimate ) - Redesign and fabrication of chassis whith emphasis put on performance. The 2018 season chassis will be smaller, lighter, and have improved handling compared to the 2017 season chassis. Because nearly all system components are know the space constraints of the 2018 car will be optimized. 

Suspension - 1500 - Redesign and fabrication of a new suspension system. This project will also take advantage of the fact that nearly all system components are know. The result will be optimization of the Hybrid racecar's vehicle kinematics to thier full potential.

Bodywork - 1500 - New outer panelling will be needed to keep our car aerodynamic, asthetically pleasing, and able to accomadate sponsors' information. 

Steering Wheel - 500 - Design and fabrication of a new electronically faceted steering wheel. A new steering wheel presents a unique design project that encompasses ergonomics, user interfacing, and integration of electrical systems. This project would also eliminate the need for a dashboard.

This list should be edited by everyone ;)

**Comment by smithbeuvic** [comment]
[ESS Club Funding Proposal UVic Hybrid Fall 2017 (1).docx](https://github.com/UVicFH/Home/files/1042495/ESS.Club.Funding.Proposal.UVic.Hybrid.Fall.2017.1.docx)

**Comment by RAKuhr** [comment]
Here is what I will be submitting:
[ESS Club Funding Proposal UVic Hybrid.docx](https://github.com/UVicFH/Home/files/1042595/ESS.Club.Funding.Proposal.UVic.Hybrid.docx)

**Comment by smithbeuvic** [comment]
just confirming the application was sent in. I dont know if your still up...

**Comment by RAKuhr** [comment]
Yes it was submitted. Email is in the team's account. 

Robert A. Kuhr
(250) 893-7628

On May 31, 2017, at 11:00 PM, smithbeuvic <notifications@github.com> wrote:

just confirming the application was sent in. I dont know if your still up...
