### ISSUE TITLE
Rainhouse ( Formerly PED ) Launch Party

### ISSUE THREAD

**Issue by smithbeuvic** [UVicFH/Home#9]
- Confirm attendance
- Confirm shipping of our car
- Organize group to be present during the Launch Party

**Comment by smithbeuvic** [comment]
Im going to confirm by email at noon, Unless anybody can see a reason that we cannot attend this event? 
Should we ask any additional questions in the email?

**Comment by chadjmccolm** [comment]
I can be there from like 12:45 to 2. I may be able to skip a class and be there earlier too, depending if I can get caught up by then. 

Question for the email: dress code?

**Comment by cweissy** [comment]
Interested in attending. I can go around 1130 if anyone wants to ride bikes over
